
language: haskell
ghc: 7.6

# TODO - use cabal or stack to compile & test
install:
    - cabal install parsec
    - cabal install tasty tasty-quickcheck
    - ghc repl.hs
    - ghc test.hs

script:
    - ./test
