name:                hscheme
version:             0.1.0.0
github:              "githubuser/hscheme"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/hscheme#readme>

dependencies:
- base >= 4.7 && < 5
# For Control.Monad.Except
- mtl == 2.2.2
- parsec >= 3.1

library:
  source-dirs: src

executables:
  hscheme-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hscheme

tests:
  hscheme-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hscheme
    - tasty == 1.0.1.1
    - tasty-quickcheck == 0.9.2
    - tasty-hunit == 0.10.0.1